server:
  port: 9000
  servlet:
    context-path: /maildemo

spring:
  application:
    name: mail-demo
  #邮件配置
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
