server:
  port: 9000
  servlet:
    context-path: /kafka-demo

spring:
  application:
    name: kafka-demo
  #kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9002
      group-id: test-consumer
      auto-offset-reset: latest