server:
  port: 9001

spring:
  application:
    name: admin-demo
  #springBoot-admin配置
  boot:
    admin:
      context-path: admin-server
      # 邮件预警配置
      notify:
        mail:
          enabled: true
            # 发件人
            from: Spring-Boot-Admin <${spring.mail.username}>
            # 收件人,如果存在多个,使用逗号分隔
            to: example@example.com
  security:
    user:
      name: admin
      password: admin
  #邮件配置
  mail:
    # 邮箱服务器地址,如QQ邮箱的为 smtp.qq.com,阿里云企业邮箱的为 smtp.qiye.aliyun.com
    host: smtp.example.com
    # 发件人帐号
    username: example@example.com
    # 发件人密码
    password: example
    # 邮箱服务器端口
    port: 587
    # 邮件协议
    protocol: smtp
    # 默认字符编码
    default-encoding: UTF-8
    # 测试配置可用性
    test-connection: true
    # 如果使用加密端口需要添加下面的配置,否则不需要
#    properties:
#      mail.smtp.ssl.enable: true
